global:
  scrape_interval: 6s

scrape_configs:
  - job_name: "api-gestao-vagas"
    metrics_path: "/actuador/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]
        labels:
          application: "api-gestao-vagas"